### ISSUE TITLE
Doesn't work on Android 8.1

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ViktorDegtyarev/CallRecLib#14]
It shows this error when pressing the FAB, which is supposed to start it:

2018-06-21 15:43:16.822 31003-31003/net.callrec.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.callrec.app, PID: 31003
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.Exception
        at net.callrec.app.CallRecProcessingNotification.makeOutputFile(CallRecProcessingNotification.kt:38)
        at net.callrec.app.ProcessingBase.startRecorder(ProcessingBase.kt:55)
        at net.callrec.app.ProcessingBase.access$startRecorder(ProcessingBase.kt:15)
        at net.callrec.app.ProcessingBase$RecorderRunnable.run(ProcessingBase.kt:190)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

Running on Android 6.0.1, I get even this (not via the FAB) :

06-21 15:46:20.645 17257-17257/net.callrec.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.callrec.app, PID: 17257
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.Exception
        at net.callrec.app.CallRecProcessingNotification.makeOutputFile(CallRecProcessingNotification.kt:38)
        at net.callrec.app.ProcessingBase.startRecorder(ProcessingBase.kt:55)
        at net.callrec.app.ProcessingBase.access$startRecorder(ProcessingBase.kt:15)
        at net.callrec.app.ProcessingBase$RecorderRunnable.run(ProcessingBase.kt:190)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:152)
        at android.app.ActivityThread.main(ActivityThread.java:5497)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
06-21 15:46:20.675 1119-17280/? D/DropBoxManagerService: file :: /data/system/dropbox/data_app_crash@1529585180665.txt
06-21 15:46:21.874 17287-17287/net.callrec.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.callrec.app, PID: 17287
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.Exception
        at net.callrec.app.CallRecProcessingNotification.makeOutputFile(CallRecProcessingNotification.kt:38)
        at net.callrec.app.ProcessingBase.startRecorder(ProcessingBase.kt:55)
        at net.callrec.app.ProcessingBase.access$startRecorder(ProcessingBase.kt:15)
        at net.callrec.app.ProcessingBase$RecorderRunnable.run(ProcessingBase.kt:190)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:152)
        at android.app.ActivityThread.main(ActivityThread.java:5497)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by MountainNine** [comment]
did you check the permission?

**Comment by AndroidDeveloperLB** [comment]
Yes. Can you please update the UI to be more intuitive ?

**Comment by MountainNine** [comment]
In Oreo, startService(X) startForegroundService(O). Check this.

Also, the version is not nougat, change typeRecorder WAV_NATIVE -> WAV.

**Comment by AndroidDeveloperLB** [comment]
Can you please update the repository?
I'm not sure I have the time...

**Comment by MountainNine** [comment]
I don't know how to update the repository.

**Comment by AndroidDeveloperLB** [comment]
ok I've set targetSdkVersion 22 , and I've granted the permissions. And this time tested on older Android version :  Tested on OnePlus 2 with Android 6.0.1. Tested outgoing call.

The service runs fine, but it creates a non-empty file on /CallReTest/ folder that can't be played.

**Comment by MountainNine** [comment]
is the record file .wav file?

**Comment by MountainNine** [comment]
If it is, change "wav" to "amr" .

**Comment by AndroidDeveloperLB** [comment]
Yes, but changing also doesn't help.
The player apps are smart enough to decide how to open the file based on the content, instead of just the extension.

**Comment by MountainNine** [comment]
change targetsdkversion 22 to 23.

**Comment by AndroidDeveloperLB** [comment]
Still doesn't work.

**Comment by MountainNine** [comment]
did you change  formatFile in prepareAudioPreferences, not in file manager?

**Comment by AndroidDeveloperLB** [comment]
No. I did it in the file manager.
I don't think it matters, because it's just file extension.
I've changed it now to this:

![image](https://user-images.githubusercontent.com/5357526/41840997-d4e3082c-786f-11e8-9c20-d965fef09a68.png)

Still has the same exact issue.
And the file extension didn't get change. It still has "wav" :
![image](https://user-images.githubusercontent.com/5357526/41841102-12f36986-7870-11e8-941a-96bcda03585f.png)

**Comment by MountainNine** [comment]
find "wav" in NativeWavRecorder and WavRecorder, and change "amr".

As I know, it cannot play the wav file in android.

**Comment by MountainNine** [comment]
I'm off work, Maybe I can send the message after 15 hour.

**Comment by KnightOfRealm** [comment]
Use different player. The native player does not support wav file format.

**Comment by AndroidDeveloperLB** [comment]
There is no "NativeWavRecorder", and I don't get what you suggest to do:

![image](https://user-images.githubusercontent.com/5357526/41842345-369eec5e-7873-11e8-99a7-70516725a000.png)

Also, if it's not supported, why put it there in the first place...

**Comment by AndroidDeveloperLB** [comment]
I've tried 4 players: 
Total Commander, Music, Google Play Music, VLC

All failed to play it.
And, Android is supposed to support wav files:
https://developer.android.com/guide/topics/media/media-formats

**Comment by MountainNine** [comment]
in library folder, NativeWavRecorder and WavRecorder class exists.

**Comment by AndroidDeveloperLB** [comment]
@MountainNine Still can't see it:
![image](https://user-images.githubusercontent.com/5357526/41893478-8abeb3b2-7924-11e8-8959-38f423a6b5ab.png)

Also:
https://github.com/ViktorDegtyarev/CallRecLib/tree/master/library/
https://github.com/ViktorDegtyarev/CallRecLib/tree/master/library/src/main/java/net/callrec/library/fix

**Comment by MountainNine** [comment]
it is in develop branch, not master branch.

**Comment by AndroidDeveloperLB** [comment]
I can't see you've mentioned using a different branch.
I can't even build this branch:
![image](https://user-images.githubusercontent.com/5357526/41895630-3cd94d7c-792b-11e8-8906-7684d381a064.png)

**Comment by MountainNine** [comment]
Is your branch 'develop'?? As I see, your branch is master.

**Comment by MountainNine** [comment]
give me telegram address.

**Comment by AndroidDeveloperLB** [comment]
Odd. But I chose "develop": 
![image](https://user-images.githubusercontent.com/5357526/41898624-35317d80-7933-11e8-818f-df653ffdd52d.png)

Tried again. Still seem to be of "master".
So I've downloaded the zip file instead, from the website.
Now I've found the classes. Is this what you wish to do:

![image](https://user-images.githubusercontent.com/5357526/41899179-7c739c9a-7934-11e8-8200-2727fc0871df.png)

If so, I don't think it can help, because extension doesn't mean the player will be able to play it.

And, just like before, for some reason I fail to build it.
This is odd, because I remember I could build the normal one (master).

**Comment by kapilip** [comment]
@MountainNine @ViktorDegtyarev I am using develop branch(tried both branches ) and still, files aren't playable. Can you help?
